version: 2
jobs:
  build:
    docker:
      - image: perl:5.28
    steps:
      - checkout
      - restore_cache:
          key: cacheminil-v2
      - run:
          name: Install Minilla
          command: |
            cpanm Minilla
      - save_cache:
          key: cacheminil-v2
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/perl5/site_perl"
      - restore_cache:
          keys:
            - cachelocal-v2-{{ checksum "cpanfile" }}
            - cachelocal-v2-
      - run:
          name: Build
          command: |
            minil build
      - save_cache:
          key: cachelocal-v2-{{ checksum "cpanfile" }}
          paths:
            - "local"
      - run:
          name: Test
          command: |
            minil test
