version: 2.1

jobs:
  test:
    parameters:
      perl-repository:
        type: string
        default: ""
      perl-version:
        type: string
    docker:
      - image: << parameters.perl-repository >>perl:<< parameters.perl-version >>
    steps:
      - checkout
      - restore_cache:
          key: cacheminil-<< parameters.perl-version >>-v1
      - run:
          name: Install Minilla
          command: |
            cpanm Minilla
      - save_cache:
          key: cacheminil-<< parameters.perl-version >>-v1
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/perl5/site_perl"
      - restore_cache:
          keys:
            - cachelocal-<< parameters.perl-version >>-v1-{{ checksum "cpanfile" }}
            - cachelocal-<< parameters.perl-version >>-v1-
      - run:
          name: Build
          command: |
            minil build
      - save_cache:
          key: cachelocal-<< parameters.perl-version >>-v1-{{ checksum "cpanfile" }}
          paths:
            - "local"
      - run:
          name: Test
          command: |
            minil test

workflows:
  build:
    jobs:
      - test:
          name: "test-latest"
          perl-version: "5.28"
      - test:
          name: "test-older"
          perl-version: "5.24"
      - test:
          name: "test-oldest"
          perl-version: "5.10.1"
          perl-repository: "hiratara/"
